import { KanboardFilter } from "./KanboardFilter.mjs"
import { formatDuration, dateToString, getDurationFromNow } from "../utils/formatDuration.mjs";
import { Kontext } from "./Kontext.mjs";
import { Workspace } from "./Workspace.mjs";
import { Project } from "./Project.mjs";
import { Swimlane } from "./Swimlane.mjs";
import { Task } from "./Task.mjs";
import { Ref } from "./Ref.mjs"

class KanbearMigrator {
  constructor(element, filtersMap) {
    this.project = Kontext.getCurrentProject()
    this.htmlElement = element
    this.kanboardFilter = new KanboardFilter(filtersMap)
    this.buttons = {}
    this.table = undefined
  }

  //-----------------------------------------------------------------
  async migrate() {
    //this.projects.forEach((project, projectIndex) => {
    let wss
    await Workspace.getAll('workspaces').then( x => wss=x)
    console.log(wss)
    wss.foreach( (ws ) => {
      console.log(` ${ws.id}:${ws.name}`)
    })
    const wsName=prompt(wssStr + "Enter workspace id (null for new) : ")
    const ws=Workspace.generate()
    ws.setName(wsName)
    ws.setDescription("Generated by migrator")
    await ws.create()
    console.log("ws id ",ws.getId())
    const pr=Project.generate()
    pr.setData("workspace_id",ws.getId())
    pr.setName(this.project.name)
    pr.setDescription(this.project.description)
    pr.setOpen(this.project.is_open)
    await pr.create()
    Object.entries(this.project.columns).forEach(([cKey, column]) => {
      //console.log("columns", column.name)
    })

    Object.entries(this.project.swimlanes).forEach(([sKey, swimlane]) => {
      
      //console.log("swimlanes", swimlane.name)
      Object.entries(swimlane.tasks).forEach(([tKey, task]) => {
        //console.log("tasks", task.name)
      })
    });

  }

}
export { KanbearMigrator }
