import { KanboardFilter } from "./KanboardFilter.mjs"
import { formatDuration, dateToString, getDurationFromNow } from "../utils/formatDuration.mjs";
import { Kontext } from "./Kontext.mjs";
import { Workspace } from "./Workspace.mjs";
import { Project } from "./Project.mjs";
import { Swimlane } from "./Swimlane.mjs";
import { Column } from "./Column.mjs";
import { KanbearEntityFactory } from "./KanbearEntityFactory.mjs";
import { Task } from "./Task.mjs";
import { Ref } from "./Ref.mjs"

class KanbearMigrator {
  constructor(element, filtersMap) {
    this.project = Kontext.getCurrentProject()
    this.htmlElement = element
    this.kanboardFilter = new KanboardFilter(filtersMap)
    this.buttons = {}
    this.table = undefined
    let resultTitle = document.createElement('h2')
    resultTitle.innerHTML = `Migrating ${this.project.name} from kanboard`
    document.getElementById(this.htmlElement).replaceChildren(resultTitle)
  }


  //----------------------------------------------------------
  //---------------------------------------------------------------------------------
  async buildTargetWorkspaceSelectBox(id, wss, labelText) {

    console.log("buildTargetWorkspaceSelectBox(id, wss)", wss)
    const wsDiv = document.createElement("div")
    wsDiv.classList.add("filter-group")
    const label = document.createElement("label")
    label.setAttribute("for", "workspace")
    label.innerHTML = labelText
    const select = document.createElement("select")
    select.setAttribute("name", "workspace")
    select.setAttribute("id", id)

    wss.forEach((ws, idx) => {
      console.log(ws)

      const option = document.createElement('option')
      if (idx == 0) {
        option.setAttribute("selected", "selected")
      }
      option.setAttribute("value", ws.id)
      option.innerHTML = ws.name
      select.appendChild(option)
    })
    wsDiv.appendChild(label)
    wsDiv.appendChild(select)
    return (wsDiv)
  }

  //-----------------------------------------------------------------
  async migrate() {
    let wss = await Workspace.getAll('workspaces')
    console.log("KanbearMigrator.migrate", wss)
    let wsDiv = await this.buildTargetWorkspaceSelectBox("targetWorspaceSelectBox", wss, "target workspace")
    document.getElementById(this.htmlElement).appendChild(wsDiv)
    document.getElementById("targetWorspaceSelectBox").addEventListener('change', (e) => {
      const targetWorkspaceId = e.target.value;
      console.log("targetWorspaceSelectBox", e.target.value)
      this.migrateProjectToWorkspace(targetWorkspaceId)
      //Kontext.setProject(selectedProject, "xxxx")
    });
  }

  //-----------------------------------------------------------------
  async migrateProjectToWorkspace(wsId) {
    //const ws = Workspace.generate()
    //ws.setName(wsName)
    //ws.setDescription("Generated by migrator")
    //await ws.create()
    console.log("ws id ", wsId)
    const pr = await KanbearEntityFactory.generate('project')
    pr.setData("workspace_id", wsId)
    pr.setName(this.project.name)
    pr.setDescription(this.project.description)
    pr.setOpen(this.project.is_open)
    await pr.create()
    console.log("Project envelop created (empty)")
    Object.entries(this.project.columns).forEach(async ([cKey, column]) => {
      console.log("columns", column.name)
      const co = await KanbearEntityFactory.generate('column')
      co.setName(column.name)
      co.setDescription(column.description)
      co.setData("position", column.position)
      co.setData("project_id", this.project.id)
      await co.create()
    })
console.log("Project columns created ")
    Object.entries(this.project.swimlanes).forEach(async ([sKey, swimlane]) => {
      console.log("swimlanes", swimlane.name)
      const sw = await KanbearEntityFactory.generate('swimlane')
      sw.setName(swimlane.name)
      sw.setDescription(swimlane.description)
      sw.setData("position", swimlane.position)
      sw.setData("project_id", this.project.id)
      //console.log("swimlanes", swimlane.name)
      await sw.create()
      console.log("Project swimlane created", swimlane.name )
      Object.entries(swimlane.tasks).forEach( async ([tKey, task]) => {
        console.log("tasks", task.name)
        const ta = await KanbearEntityFactory.generate('task')
        ta.setName(task.name)
        ta.setDescription(task.description)
        ta.setData("position", task.position)
        ta.setData("project_id", this.project.id)
        ta.setData("project_id", sw.getId())
        //console.log("swimlanes", swimlane.name)
        await ta.create()
        //console.log("tasks", task.name)
      })
      console.log("Project tasks created")
    });
    alert("Projet migrated")
  }

}
export { KanbearMigrator }
